FROM centos:7

LABEL VERSION 2.3.7.2

RUN set -x \
    && groupadd -g 89 postfix \
    && groupadd -g 90 postdrop \
    && useradd -u 89 -g postfix -d /opt/postfix -s /sbin/nologin -M postfix \
    && groupadd -g 700 vmail \
    && useradd -d /home/dominios -s /sbin/nologin -g vmail -M -u 700 vmail \
    && groupadd dovecot \
    && groupadd dovenull \
    && useradd -d /opt/dovecot -s /bin/false -g dovecot -M dovecot \
    && useradd -d /opt/dovecot -s /bin/false -g dovenull -M dovenull \
    \
	&& yum -y install gcc \
	&& yum -y install make \
    && yum -y install wget \
    && yum -y install openssl-devel \
    && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum -y install supervisor \
    \
    && cd /usr/local/src \
    && wget https://dovecot.org/releases/2.3/dovecot-2.3.7.2.tar.gz \
    && tar xzvf dovecot-2.3.7.2.tar.gz \
    && rm dovecot-2.3.7.2.tar.gz \
    && cd dovecot-2.3.7.2 \
    && ./configure \
        --prefix=/opt/dovecot \
        --without-shadow \
        --without-pam \
        --without-gssapi \
        --without-ldap \
        --without-mysql \
        --without-pgsql \
        --without-sqlite \
    \
    && cd /usr/local/src/dovecot-2.3.7.2 \
    && make \
    && make install \
    \
    && echo PATH=/opt/dovecot/bin/:/opt/dovecot/sbin/:$PATH > /etc/profile.d/path.sh \
    && cp -av /opt/dovecot/share/doc/dovecot/example-config/* /opt/dovecot/etc/dovecot \
    && mkdir /var/log/dovecot \
    && chown dovecot.dovecot /var/log/dovecot \
    \
    && cd /tmp \
    && curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" \
    && python get-pip.py \
    && rm /tmp/get-pip.py \
    && pip install -U certbot \
    && pip install --upgrade setuptools \
    && echo "#!/bin/bash" >> /usr/local/bin/certbot \
    && echo "" >> /usr/local/bin/certbot \
    && echo "/usr/bin/certbot certonly --standalone \$@" >> /usr/local/bin/certbot \
    && chmod 755 /usr/local/bin/certbot \
    \
    && yum -y remove gcc \
    && yum -y remove make \
    && yum -y remove openssl-devel \
    && yum -y remove wget \
    && yum clean all

COPY files /

ENV NAME="mail.midominio.com" \
    SSL="no" \
    AUTH="yes" \
    PROTOCOLS="imap pop3 lmtp submission" \
    POP3="yes" \
    POP3S="yes" \
    IMAP="yes" \
    IMAPS="yes" \
    LMTP="yes" \
    SUBMISSION="no" \
    SUBMISSION_HOST="localhost" \
    AUTH_DEBUG="no" \
    AUTH_DEBUG_PASSWORDS="no"

# volumes:
#       - /home/dominios:/home/dominios
#       - /etc/letsencrypt:/etc/letsencrypt
#       - ./etc:/opt/dovecot/conf
#       - ./log:/var/log/dovecot

CMD /opt/dovecot/env.sh && /opt/dovecot/sbin/dovecot -F
