FROM centos:7

LABEL VERSION 2.3.7.2

RUN set -x \
    && yum update -y \
    \
    && groupadd -g 89 postfix \
    && groupadd -g 90 postdrop \
    && useradd -u 89 -g postfix -d /opt/postfix -s /sbin/nologin -M postfix \
    && groupadd -g 700 vmail \
    && useradd -d /home/dominios -s /sbin/nologin -g vmail -M -u 700 vmail \
    && groupadd dovecot \
    && groupadd dovenull \
    && useradd -d /opt/dovecot -s /bin/false -g dovecot -M dovecot \
    && useradd -d /opt/dovecot -s /bin/false -g dovenull -M dovenull \
    \
	&& yum -y install gcc \
	&& yum -y install make \
    && yum -y install wget \
    && yum -y install openssl-devel \
	&& yum -y install m4 \
    && yum -y install wget \
    && yum -y install libdb-devel \
    && yum -y install pcre-devel \
    && yum -y install openssl-devel \
    \
    && cd /usr/local/src \
    && wget https://dovecot.org/releases/2.3/dovecot-2.3.7.2.tar.gz \
    && tar xzvf dovecot-2.3.7.2.tar.gz \
    && rm dovecot-2.3.7.2.tar.gz \
    && cd dovecot-2.3.7.2 \
    && ./configure \
        --prefix=/opt/dovecot \
        --without-shadow \
        --without-pam \
        --without-gssapi \
        --without-ldap \
        --without-mysql \
        --without-pgsql \
        --without-sqlite \
    \
    && cd /usr/local/src/dovecot-2.3.7.2 \
    && make \
    && make install \
    \
    && cd /usr/local/src \
    && wget https://pigeonhole.dovecot.org/releases/2.3/dovecot-2.3-pigeonhole-0.5.7.2.tar.gz \
    && tar xzvf dovecot-2.3-pigeonhole-0.5.7.2.tar.gz \
    && rm dovecot-2.3-pigeonhole-0.5.7.2.tar.gz \
    && cd dovecot-2.3-pigeonhole-0.5.7.2 \
    && ./configure \
        --prefix=/opt/pigeonhole \
        --with-dovecot=/opt/dovecot/lib/dovecot \
    && make \
    && make install \
    \
    && cp -av /opt/dovecot/share/doc/dovecot/example-config/* /opt/dovecot/etc/dovecot \
    && mkdir /var/log/dovecot \
    && chown dovecot.dovecot /var/log/dovecot \
    \
    \
    && cd /usr/local/src \
    && wget http://ftp.uma.es/mirror/postfix/src/official/postfix-3.4.7.tar.gz \
    && tar xzvf postfix-3.4.7.tar.gz \
    && rm postfix-3.4.7.tar.gz \
    && cd postfix-3.4.7 \
    \
    && make makefiles CCARGS='-DDEF_CONFIG_DIR=\"/opt/postfix/etc\" \
        -DDEF_COMMAND_DIR=\"/opt/postfix/bin\" \
        -DDEF_DAEMON_DIR=\"/opt/postfix/daemon\" \
        -DDEF_DATA_DIR=\"/opt/postfix/data\" \
        -DDEF_MAILQ_PATH=\"/opt/postfix/bin/mailq\" \
        -DDEF_NEWALIAS_PATH=\"/opt/postfix/bin/newaliases\" \
        -DDEF_QUEUE_DIR=\"/opt/postfix/spool\" \
        -DDEF_SENDMAIL_PATH=\"/usr/sbin/sendmail\" \
        -DUSE_SASL_AUTH \
        -DDEF_SERVER_SASL_TYPE=\"dovecot\" \
        -DHAS_PCRE -I/usr/local/include \
        -DUSE_TLS ' \
        AUXLIBS='-lssl -lcrypto -lpcre' \
    \
    && make \
    && make install -non-interactive \
    && /bin/sh postfix-install -non-interactive \
    \
    && /opt/postfix/bin/newaliases \
    && ln -s /opt/postfix/bin/postmap /usr/local/bin \
    && echo PATH=/opt/postfix/bin/:$PATH > /etc/profile.d/path.sh \
    \
    \
    && yum -y remove gcc \
    && yum -y remove make \
    && yum -y remove openssl-devel \
    && yum -y remove wget \
    && yum -y remove m4 \
    && yum -y remove libdb-devel \
    && yum clean all


COPY files /


ENV NAME="mail.midominio.com" \
    SSL="no" \
    AUTH="yes" \
    POP3="yes" \
    POP3S="yes" \
    IMAP="yes" \
    IMAPS="yes" \
    LMTP="no" \
    SIEVE="no" \
    SIEVE_SMTP="mx.existo.net" \
    SUBMISSION="no" \
    DOVEADM="no" \
    DOVEADM_PORT="" \
    DOVEADM_PASSWORD="" \
    MASTER_PASSWORD="no" \
    SUBMISSION_HOST="localhost" \
    AUTH_DEBUG="no" \
    AUTH_DEBUG_PASSWORDS="no" \
    AUTH_POLICY_SERVER=""

EXPOSE 24 110 143 587 943 953 10005

# volumes:
#       - /home/dominios:/home/dominios
#       - /etc/letsencrypt:/etc/letsencrypt
#       - ./etc:/opt/dovecot/conf
#       - ./log:/var/log/dovecot

WORKDIR /opt/dovecot

CMD /opt/dovecot/env.sh && /opt/dovecot/sbin/dovecot -F
