FROM centos:7

LABEL VERSION 2.3.7.2

RUN set -x \
    && yum update -y \
    && groupadd -g 89 postfix \
    && groupadd -g 90 postdrop \
    && useradd -u 89 -g postfix -d /opt/postfix -s /sbin/nologin -M postfix \
    && groupadd -g 700 vmail \
    && useradd -d /home/dominios -s /sbin/nologin -g vmail -M -u 700 vmail \
    && groupadd dovecot \
    && groupadd dovenull \
    && useradd -d /opt/dovecot -s /bin/false -g dovecot -M dovecot \
    && useradd -d /opt/dovecot -s /bin/false -g dovenull -M dovenull \
    \
	&& yum -y install gcc \
	&& yum -y install make \
    && yum -y install wget \
    && yum -y install openssl-devel \
    \
    && cd /usr/local/src \
    && wget https://dovecot.org/releases/2.3/dovecot-2.3.7.2.tar.gz \
    && tar xzvf dovecot-2.3.7.2.tar.gz \
    && rm dovecot-2.3.7.2.tar.gz \
    && cd dovecot-2.3.7.2 \
    && ./configure \
        --prefix=/opt/dovecot \
        --without-shadow \
        --without-pam \
        --without-gssapi \
        --without-ldap \
        --without-mysql \
        --without-pgsql \
        --without-sqlite \
    \
    && cd /usr/local/src/dovecot-2.3.7.2 \
    && make \
    && make install \
    \
    && cd /usr/local/src \
    && wget https://pigeonhole.dovecot.org/releases/2.3/dovecot-2.3-pigeonhole-0.5.7.2.tar.gz \
    && tar xzvf dovecot-2.3-pigeonhole-0.5.7.2.tar.gz \
    && rm dovecot-2.3-pigeonhole-0.5.7.2.tar.gz \
    && cd dovecot-2.3-pigeonhole-0.5.7.2 \
    && ./configure \
        --prefix=/opt/pigeonhole \
        --with-dovecot=/opt/dovecot/lib/dovecot \
    && make \
    && make install \
    \
    && cp -av /opt/dovecot/share/doc/dovecot/example-config/* /opt/dovecot/etc/dovecot \
    && mkdir /var/log/dovecot \
    && chown dovecot.dovecot /var/log/dovecot \
    \
    && yum -y remove gcc \
    && yum -y remove make \
    && yum -y remove openssl-devel \
    && yum -y remove wget \
    && yum clean all

COPY files /

ENV NAME="mail.midominio.com" \
    SSL="no" \
    AUTH="yes" \
    POP3="yes" \
    POP3S="yes" \
    IMAP="yes" \
    IMAPS="yes" \
    LMTP="yes" \
    SIEVE="yes" \
    SUBMISSION="no" \
    SUBMISSION_HOST="localhost" \
    AUTH_DEBUG="no" \
    AUTH_DEBUG_PASSWORDS="no"

# volumes:
#       - /home/dominios:/home/dominios
#       - /etc/letsencrypt:/etc/letsencrypt
#       - ./etc:/opt/dovecot/conf
#       - ./log:/var/log/dovecot

WORKDIR /opt/dovecot

CMD /opt/dovecot/env.sh && /opt/dovecot/sbin/dovecot -F
