FROM existo/dovecot:2.3.6

COPY files /

# NAME = nombre del servidor
# SSL = ["yes"|"no"] si lleva SSL
ENV NAME                 = "mail.midominio.com" \
    SSL                  = "no" \
    AUTH_DEBUG           = "no" \
    AUTH_DEBUG_PASSWORDS = "no"

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
